# Generated by Django 4.1.3 on 2022-12-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppForm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='nombre_Persona',
            new_name='nombre_persona',
        ),
        migrations.AlterField(
            model_name='persona',
            name='dni',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.CharField(max_length=10),
        ),
    ]
