# Generated by Django 4.1.3 on 2022-12-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppForm', '0002_rename_nombre_persona_persona_nombre_persona_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='dni',
            field=models.IntegerField(),
        ),
    ]
