# Generated by Django 4.1.3 on 2022-12-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppForm', '0004_alter_persona_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.CharField(max_length=10),
        ),
    ]
